export default {
  results: [
    {
      id: 1,
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "How many colors are there in a rainbow?",
      correct_answer: "7",
      incorrect_answers: ["8", "9", "10"],
    },
    {
      id: 2,
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "How many colors are there in a rainbow?",
      correct_answer: "7",
      incorrect_answers: ["8", "9", "10"],
    },
    {
      id: 3,
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "How many colors are there in a rainbow?",
      correct_answer: "7",
      incorrect_answers: ["8", "9", "10"],
    },
    {
      id: 4,
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "How many colors are there in a rainbow?",
      correct_answer: "7",
      incorrect_answers: ["8", "9", "10"],
    },
    {
      id: 5,
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "How many colors are there in a rainbow?",
      correct_answer: "7",
      incorrect_answers: ["8", "9", "10"],
    },
    {
      id: 6,
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "How many colors are there in a rainbow?",
      correct_answer: "7",
      incorrect_answers: ["8", "9", "10"],
    },
  ],
};
